# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Employee:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$cvreISypKTsGj6mjQ8NwaOfrXPU5L4qlNltOieUUm2IVgNAldMPq6
                        roles: ROLE_ADMIN

        in_db:
            entity:
                class: AppBundle:Employee
                property: name

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: in_db
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: sign_in
                check_path: sign_in
                # csrf_parameter:       _csrf_token
                # csrf_token_id:        authenticate
                # csrf_token_generator: my.csrf_token_generator.id
                remember_me: true
            logout:
                path: /logout
                target: /

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_LICIT: ROLE_LICIT
        ROLE_FINANCE: [ROLE_LICIT,ROLE_FINANCE]
        ROLE_HR: [ROLE_LICIT,ROLE_HR]
        ROLE_SUPER: [ROLE_LICIT,ROLE_FINANCE,ROLE_HR,ROLE_SUPER]

    access_control:
        - { path: /login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_SUPER }
        - { path: ^/setting, roles: ROLE_LICIT }
        - { path: ^/setting1, roles: ROLE_HR }
