<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyRepository extends EntityRepository
{
}
